# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170324_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimate',
            field=models.DateField(),
        ),
    ]
